# Generated by Django 4.0.6 on 2022-12-14 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='landdata',
            name='land_data_type',
            field=models.CharField(choices=[('TR', 'Train'), ('TE', 'Test')], default=0, max_length=5),
            preserve_default=False,
        ),
    ]
