# Generated by Django 4.1 on 2022-12-15 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_landdata_land_data_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='landdata',
            name='land_data_soil_type',
            field=models.CharField(max_length=30),
        ),
    ]
