# Generated by Django 4.1 on 2022-12-16 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_landdata_land_data_soil_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='landdata',
            name='land_data_suitability',
            field=models.CharField(max_length=55),
        ),
    ]
