# Generated by Django 4.1 on 2022-12-31 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_landdata_land_data_suitability'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='employee_class',
            field=models.CharField(max_length=35),
        ),
    ]
